Zbruev_DA_task1
alvls/mp1-2021-1 pull request #1
Opened 2021-02-20 16:26 UTC by DenisZbruev

2021-02-27 20:44 UTC, alvls requested changes

2021-02-27 20:44 UTC, alvls commented on Zbruev_DA/task1/Source.cpp
> +		std::cout << "������� ����� - ������� ���, ����� ������ � �������, ������ ��� ������� enter: ";
Здесь и далее, в методах класса не должно быть ввода с консоли. Он должен происходить в другом месте (например, в main).

2021-02-27 20:44 UTC, alvls commented on Zbruev_DA/task1/Source.cpp
> +		std::cout <<"�������: "<< abs(hours-h)<<":"<< abs(minutes - m) << ":"<<abs(seconds - s)<<'\n';
1. Разница должна возращаться, а не выводиться на экран.
2. Разница считается неверно. Попробуйте ввести времена: 1:1:59 и 1:2:1. Разница д.б. 2 секунды, а у вас будет 1 минута 58 секунд.

2021-03-01 15:47 UTC, DenisZbruev commented
  27.02.2021, 23:45, "Alexander Sysoyev" <notifications@github.com>: @alvls requested changes on this pull request.In Zbruev_DA/task1/Source.cpp:> +	int minutes;
+	int hours;
+public:
+	Time(int s, int m, int h)//�����������
+	{
+		seconds = s;
+		minutes = m;
+		hours = h;
+	}
+	int getseconds() { return seconds; }//��������?
+	int getminutes() {
+	return minutes;
+	}//������� ��� ������ � ������� ������
+	int gethours() { return hours; }
+	void set_time() {//��������� �������
+		std::cout << "������� ����� - ������� ���, ����� ������ � �������, ������ ��� ������� enter: ";
Здесь и далее, в методах класса не должно быть ввода с консоли. Он должен происходить в другом месте (например, в main).In Zbruev_DA/task1/Source.cpp:> +		while ((h >= 24) || (h < 0))
+		{
+			std::cout << "������� ������ ���, ����������� ������: ";
+			std::cin >> h;
+		}
+		while ((m >= 60) || (m < 0))
+		{
+			std::cout << "������� ������� ������, ����������� ������: ";
+			std::cin >> m;
+		}
+		while ((s >= 60) || (s < 0))
+		{
+			std::cout << "������� ������� �������, ����������� ������: ";
+			std::cin >> s;
+		}
+		std::cout <<"�������: "<< abs(hours-h)<<":"<< abs(minutes - m) << ":"<<abs(seconds - s)<<'\n';
Разница должна возращаться, а не выводиться на экран.Разница считается неверно. Попробуйте ввести времена: 1:1:59 и 1:2:1. Разница д.б. 2 секунды, а у вас будет 1 минута 58 секунд.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-01 19:22 UTC, alvls requested changes

2021-03-01 19:22 UTC, alvls commented on Zbruev_DA/task1/Source.cpp
> +		while (((flag==1)&&((hours+h) >= 24)) || ((flag == 0) && (((hours - h) < 0))))
Зачем в этом методе циклы while?
Вместо возврата, лучше обработать "переполнение"

2021-03-01 19:22 UTC, alvls commented on Zbruev_DA/task1/Source.cpp
> +		return (sum1-sum2);//���������� ������� � ��������
Как вы думаете, удобно человеку получить ответ в виде разницы в 9323 секунды?

2021-03-01 19:41 UTC, DenisZbruev commented
  01.03.2021, 22:22, "Alexander Sysoyev" <notifications@github.com>: @alvls requested changes on this pull request.In Zbruev_DA/task1/Source.cpp:> +		seconds = s;
+		minutes = m;
+		hours = h;
+	}
+	
+	int raznica(int h, int m, int s)//���������� �������
+	{
+		int sum1=0;
+		int sum2 = 0;
+		sum1 = h * 3600 + m * 60 + s;//����� ������ ��� �������, ����������� � ������ 
+		sum2 = hours * 3600 + minutes * 60 + seconds;//����� ������ ��� �������, ���������� � ����������
+		return (sum1-sum2);//���������� ������� � �������� 
+	}
+	int move(int h, int m, int s, bool flag)//����� �������
+	{
+		while (((flag==1)&&((hours+h) >= 24)) || ((flag == 0) && (((hours - h) < 0))))
Зачем в этом методе циклы while?Вместо возврата, лучше обработать "переполнение"In Zbruev_DA/task1/Source.cpp:> +	int getminutes() {return minutes;}
+	int gethours() {return hours; }//������� ��� ������ � ������� ������(������ �����)
+	void settime(int h, int m, int s)//��������� �������
+	{
+		seconds = s;
+		minutes = m;
+		hours = h;
+	}
+	
+	int raznica(int h, int m, int s)//���������� �������
+	{
+		int sum1=0;
+		int sum2 = 0;
+		sum1 = h * 3600 + m * 60 + s;//����� ������ ��� �������, ����������� � ������ 
+		sum2 = hours * 3600 + minutes * 60 + seconds;//����� ������ ��� �������, ���������� � ����������
+		return (sum1-sum2);//���������� ������� � �������� 
Как вы думаете, удобно человеку получить ответ в виде разницы в 9323 секунды?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-01 19:44 UTC, DenisZbruev commented
насчет первого замечания я правильно вас понял, что если, например, ввели 25 часов, то делаем деление по модулю 24 и т.д? 01.03.2021, 22:22, "Alexander Sysoyev" <notifications@github.com>: @alvls requested changes on this pull request.In Zbruev_DA/task1/Source.cpp:> +		seconds = s;
+		minutes = m;
+		hours = h;
+	}
+	
+	int raznica(int h, int m, int s)//���������� �������
+	{
+		int sum1=0;
+		int sum2 = 0;
+		sum1 = h * 3600 + m * 60 + s;//����� ������ ��� �������, ����������� � ������ 
+		sum2 = hours * 3600 + minutes * 60 + seconds;//����� ������ ��� �������, ���������� � ����������
+		return (sum1-sum2);//���������� ������� � �������� 
+	}
+	int move(int h, int m, int s, bool flag)//����� �������
+	{
+		while (((flag==1)&&((hours+h) >= 24)) || ((flag == 0) && (((hours - h) < 0))))
Зачем в этом методе циклы while?Вместо возврата, лучше обработать "переполнение"In Zbruev_DA/task1/Source.cpp:> +	int getminutes() {return minutes;}
+	int gethours() {return hours; }//������� ��� ������ � ������� ������(������ �����)
+	void settime(int h, int m, int s)//��������� �������
+	{
+		seconds = s;
+		minutes = m;
+		hours = h;
+	}
+	
+	int raznica(int h, int m, int s)//���������� �������
+	{
+		int sum1=0;
+		int sum2 = 0;
+		sum1 = h * 3600 + m * 60 + s;//����� ������ ��� �������, ����������� � ������ 
+		sum2 = hours * 3600 + minutes * 60 + seconds;//����� ������ ��� �������, ���������� � ����������
+		return (sum1-sum2);//���������� ������� � �������� 
Как вы думаете, удобно человеку получить ответ в виде разницы в 9323 секунды?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-01 19:49 UTC, alvls commented
Да, вы поняли верно. Не вставляйте в ваши комментарии "полотна" кода - замусоривается лента.

2021-03-02 20:16 UTC, alvls commented
Денис, вы будете исправлять? Или мне оценивать текущую версию?

2021-03-02 20:18 UTC, DenisZbruev commented
в течение получаса отправлю, прошу прощения за задержку 02.03.2021, 23:16, "Alexander Sysoyev" <notifications@github.com>: Денис, вы будете исправлять? Или мне оценивать текущую версию?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-02 20:42 UTC, DenisZbruev commented
  02.03.2021, 23:16, "Alexander Sysoyev" <notifications@github.com>: Денис, вы будете исправлять? Или мне оценивать текущую версию?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-05 10:06 UTC, alvls commented
Денис, в методе raznica так и не исправили. Перевод в часы, минуты и секунды в main это, конечно, хорошо, но лучше бы вы вернули объект Time из метода.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 2,7
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 5,7

2021-03-07 09:21 UTC, closed without merging