SolutionTask2 ShushpanovNM
alvls/mp1-2021-1 pull request #14
Opened 2021-03-06 10:43 UTC by n1k1tkooo

2021-03-12 19:59 UTC, alvls requested changes

2021-03-12 19:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +		if (str[index] != ' ')
Почему сравниваете с пробелом?

2021-03-12 19:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +	void EditCharByIndexString(int index, char *symbol)
Зачем передаете символ по указателю, а не по значению?

2021-03-12 19:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +		cout << "\n������ ���������: " << sizeSub << endl;
Зачем здесь вывод на экран?

2021-03-12 19:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +				return false;
А где return true?

2021-03-12 19:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +		return count;
Ваша реализация считает число разных символов вообще в строке, а не число латинских символов.

2021-03-13 17:41 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +		if (str[index] != ' ')
Чтобы не выводить пустой символ, а пользователю написать "Что символа в данной позиции нет, это пробел"

2021-03-13 17:43 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +		cout << "\n������ ���������: " << sizeSub << endl;
Не знаю, посчитал что так будет правильнее. Исправил.

2021-03-13 17:44 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +		if (str[index] != ' ')
Не нужно этого делать, пробел в строке - такой же символ, как и остальные. Его также нужно возвращать.

2021-03-13 17:45 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +		if (str[index] != ' ')
Хорошо, исправил

2021-03-13 17:57 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +				return false;
Исправил

2021-03-13 17:58 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +		return count;
Получается, я должен посчитать сколько каждой буквы встречается в строке?

2021-03-13 17:59 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +		return count;
Нужно считать только латинские символы в строке, все остальные игнорировать.

2021-03-13 21:09 UTC, alvls requested changes

2021-03-13 21:09 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Почему возвращаете char*, а не Строку?

2021-03-13 21:09 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +				return false;
Исправили неверно.

2021-03-14 11:56 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Не совсем понял в чем ошибка

2021-03-14 14:32 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Ошибка в том, что нужно вернуть объект класса Строка. Подстрока - это объект того же класса.

2021-03-14 15:09 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Я правильно понял, я создаю в классе две дополнительные переменные и буду записывать в них подстроку?

2021-03-14 15:22 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Почему две переменных? Одну переменную типа Строка

2021-03-14 15:24 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Я в главном методе создаю новый объект типа стринг и в него уже записываю подстроку, правильно?

2021-03-14 16:22 UTC, alvls commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Вот такой д.б. прототип:

    String SubstringFromAString(int indexLeft, int indexRight);

2021-03-14 16:35 UTC, n1k1tkooo commented on shushpanov_nm/task2/Source.cpp
> +	char* SubstringFromAString(int indexLeft, int indexRight)
Аааа, дошло, спасибо

2021-03-14 20:25 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2021-03-14 20:25 UTC, merged