smirnov_av_task2_vecTOR
alvls/mp1-2021-1 pull request #15
Opened 2021-03-06 17:38 UTC by YoungPinch

2021-03-12 20:27 UTC, alvls requested changes

2021-03-12 20:27 UTC, alvls commented on smirnov_av/task2/_vector.h
> +		size = 0;
После деструктора поля станут недоступны, нет смысла их обнулять.

2021-03-12 20:27 UTC, alvls commented on smirnov_av/task2/_vector.h
> +			this->vec = new int[size];
А где удаление "старой" памяти?

2021-03-12 20:27 UTC, alvls commented on smirnov_av/task2/_vector.h
> +	long ScalarProduct(Vector vec2)
Лучше принять по конст ссылке

2021-03-12 20:27 UTC, alvls commented on smirnov_av/task2/_vector.h
> +		size = vec2.size;
А где перевыделение памяти?

2021-03-13 16:41 UTC, alvls requested changes

2021-03-13 16:41 UTC, alvls commented on smirnov_av/task2/_vector.h
> +			if (this->size > size)
Выше у вас this->size = size;
Т.о. это и следующее условие никогда не выполнятся.

2021-03-13 16:41 UTC, alvls commented on smirnov_av/task2/_vector.h
> +		size = vec2.size;
Я писал про перевыделение, а не выделение. Старую память вы потеряли.

2021-03-13 17:57 UTC, YoungPinch commented on smirnov_av/task2/_vector.h
> +			if (this->size > size)
Да, глупо вышло. А как студия вообще смогла скомпилировать такой код?

2021-03-13 18:04 UTC, alvls commented on smirnov_av/task2/_vector.h
> +			if (this->size > size)
С точки зрения компилятора здесь нет ошибок.

2021-03-13 21:14 UTC, alvls requested changes

2021-03-13 21:14 UTC, alvls commented on smirnov_av/task2/_vector.h
> +	void ChangeSize(short size)
Не называйте параметры методов также как поля. Во-первых, трудно читать. Во-вторых, использовать this->, чтобы отличать поле от параметра - плохой тон. И, наконец, там где this не указан, нет гарантии, что компилятор правильно поймет ваши ожидания.

2021-03-14 08:32 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 6,2

2021-03-14 08:32 UTC, merged