task 2 Krainev
alvls/mp1-2021-1 pull request #16
Opened 2021-03-06 17:56 UTC by AlexanderOfficial

2021-03-12 20:43 UTC, alvls requested changes

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	int get_length();
Во всех остальных именах символа _ у вас нет.

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	char gettingSymbolByIndex(int index);
В остальных именах глаголы, а здесь нет

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	void extractАSubstringАromАString(int left, int lenSub);
Выделить строку - значит вернуть ее, а не вывести на экран.

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	void countCharikov();//
Смените имя

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	bool polyindromeCheck();
Смените имя на единообразное в остальными

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	str[0] = '\n';//строка по умолчанию
Почему `\n'`?

2021-03-12 20:43 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +			cout << "Переданная строка : " << str << endl;
Зачем вывод на экран?

2021-03-12 21:31 UTC, alvls requested changes

2021-03-12 21:31 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	char* extractАSubstringАromАString(int left, int lenSub);
1. Слишком длинное имя. Достаточно `extractSubstring`
2. Почему возвращаете char*?

2021-03-12 21:31 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	void countCharInAString();//
Слишком длинное имя. Достаточно `countChar`. Итак понятно, что символы считаются в строке.

2021-03-13 09:00 UTC, alvls requested changes

2021-03-13 09:00 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	void extractSubstring(int left, int lenSub, char* sub);
Проблема с методом была не в том, что он возвращал строку через возвращаемое значение, а в том, что подстрока - это тоже строка. Нужно вернуть тип String

2021-03-13 09:25 UTC, AlexanderOfficial commented on Krainev_AA/task2/Source.cpp
> +	void extractSubstring(int left, int lenSub, char* sub);
Но ведь новое решение тоже нормальное? или лучше переделать?

2021-03-13 12:12 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +	void extractSubstring(int left, int lenSub, char* sub);
Лучше переделать. Класс Строка для того и пишется, чтобы работать через него. Возвращать С-строку нужно только тогда, когда ее нужно передать в старые сишные функции.

2021-03-14 14:41 UTC, alvls requested changes

2021-03-14 14:41 UTC, alvls commented on Krainev_AA/task2/Source.cpp
> +void String::extractSubstring(int left, int lenSub, String* sub)
И все-таки снова не так. Вот такой должен быть прототип:

    String String::extractSubstring(int left, int lenSub)

Соответственно подстрока должна формироваться в методе и возвращаться из него.

2021-03-15 14:49 UTC, alvls commented
__Работа принята__ |  
-- | --
__Ваш текущий   балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество   кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2021-03-15 14:52 UTC, alvls commented
Александр, использовать static для локальной переменной в extractSubstring не было необходимости. На будущее учтите.

2021-03-15 14:52 UTC, merged