Solution of task 2
alvls/mp1-2021-1 pull request #17
Opened 2021-03-06 19:01 UTC by DDYunin

2021-03-12 21:21 UTC, alvls requested changes

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	int age;
age - возраст. тут лучше использовать year

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	void GetNamesEvents()
Почему множественное число?

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +		cout << "������� ������� �����������!" << endl;
Зачем вывод на экран

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	void GetDataEvent()
Выведенную на экран дату нельзя использовать программно. Метод должен вернуть дату.

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	void CoutingDaysDate(int & days,int & daysn,Calendarofevents & other ,int i = 0)
Здесь и далее лучше использовать глагол в имени метода

2021-03-12 21:21 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	int month;
У вас в классе может храниться только одно событие, а должно храниться много.

2021-03-13 06:17 UTC, DDYunin commented on Yunin_DD/task2/TaskProgram2.cpp
> +		cout << "������� ������� �����������!" << endl;
Чтобы пользователь знал, что событие было успешно добавлено. Его лучше поместить не в класс, а в функцию, после вызова определённого метода?

2021-03-13 06:52 UTC, DDYunin commented on Yunin_DD/task2/TaskProgram2.cpp
> +	int month;
Александр Владимирович, а здесь я правильно понимаю, что в самом классе должен быть указан указатель типа моего класса? И вследствие почти все функции, что используют динамический массив перенести непосредственно в класс?

2021-03-13 09:01 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +		cout << "������� ������� �����������!" << endl;
> Его лучше поместить не в класс, а в функцию, после вызова определённого метода?

Да.

2021-03-13 09:02 UTC, alvls commented on Yunin_DD/task2/TaskProgram2.cpp
> +	int month;
Именно так.

2021-03-14 09:07 UTC, alvls commented
Теперь почти все хорошо, кроме того, что число событий, которое хранится в календаре, сам календарь почему-то не знает. Так быть не должно. У вас объект получается зависим от внешнего окружения.

2021-03-14 14:30 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2021-03-14 14:31 UTC, merged