Zbruev_DA_task2
alvls/mp1-2021-1 pull request #22
Opened 2021-03-07 09:22 UTC by DenisZbruev

2021-03-13 17:08 UTC, alvls requested changes

2021-03-13 17:08 UTC, alvls commented on Zbruev_DA/task2/Source.cpp
> +		matr = (int**)malloc(sizeof(int) * size*size);
Используйте new вместо malloc
matr = new (int*)[size];
Далее аналогично

2021-03-13 17:08 UTC, alvls commented on Zbruev_DA/task2/Source.cpp
> +		free(matr);
Используйте delete.

2021-03-13 17:08 UTC, alvls commented on Zbruev_DA/task2/Source.cpp
> +	void getmatr(int num1, int num2, int elem)//������������� ������� �� ������
Перепутаны названия. Это метод типа set, а следующий типа get

2021-03-13 20:00 UTC, DenisZbruev commented
Александр Владимирович, я пытался использовать new/delete, но у меня постоянно программа падала. А с malloc почему-то все прекрасно работает 13.03.2021, 20:09, "Alexander Sysoyev" ***@***.******@***.*** requested changes on this pull request.In Zbruev_DA/task2/Source.cpp:> @@ -0,0 +1,233 @@
+#include <clocale>
+#include <iostream>
+#include <cmath>
+#include <cstdlib>
+#define N 8//����� ������� � ���� 
+class Matrix
+{
+	int** matr;
+	int size=0;//����� �����
+public:
+	Matrix(int razmer)//�����������
+	{
+		int i, j;
+		size = razmer;
+		matr = (int**)malloc(sizeof(int) * size*size);
Используйте new вместо mallocmatr = new (int*)[size];Далее аналогичноIn Zbruev_DA/task2/Source.cpp:> +		for (i = 0; i < size; i++) {//����������� ������ ������, ����� �������� ����� (��� ���� ������ �� ���������)
+			free(matr[i]);
+		}
+		free(matr);
Используйте delete.In Zbruev_DA/task2/Source.cpp:> +			for (j = 0; j < size; j++)
+				matr[i][j] = 0;
+	}
+	Matrix(const Matrix &m)//����������� �����������
+	{
+		size = m.size;
+		matr = (int**)malloc(sizeof(int) * size * size);
+		for (int i = 0; i < size; i++)
+		{
+			matr[i] = (int*)malloc(sizeof(int) * size);
+		}
+		for (int i = 0; i < size; i++)
+			for (int j = 0; j < size; j++)
+				matr[i][j] = m.matr[i][j];
+	}
+	void getmatr(int num1, int num2, int elem)//������������� ������� �� ������
Перепутаны названия. Это метод типа set, а следующий типа get—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-13 20:27 UTC, alvls commented
Хорошо, оставьте в этот раз malloc/free. Но 1) исправьте ошибку в выделении памяти в конструкторе, 2) исправьте названия методов.

2021-03-13 22:30 UTC, DenisZbruev commented
Исправил 13.03.2021, 23:27, "Alexander Sysoyev" ***@***.***>: Хорошо, оставьте в этот раз malloc/free. Но 1) исправьте ошибку в выделении памяти в конструкторе, 2) исправьте названия методов.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-14 14:50 UTC, alvls requested changes

2021-03-14 14:50 UTC, alvls commented on Zbruev_DA/task2/Source.cpp
> +		matr = (int**)malloc(sizeof(int*) * size * size);
Одну ошибку исправили, вторую - нет.

2021-03-14 20:17 UTC, DenisZbruev commented
Действительно, я не доглядел. Но сейчас исправил, спасибо за ожидание 14.03.2021, 17:50, "Alexander Sysoyev" ***@***.******@***.*** requested changes on this pull request.In Zbruev_DA/task2/Source.cpp:> @@ -12,8 +12,8 @@ class Matrix
 	{
 		int i, j;
 		size = razmer;
-		matr = (int**)malloc(sizeof(int) * size*size);
-		for (int i = 0; i < /*size1*/size; i++)
+		matr = (int**)malloc(sizeof(int*) * size * size);
Одну ошибку исправили, вторую - нет.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-14 20:48 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2021-03-14 20:48 UTC, merged