task2 alser3217
alvls/mp1-2021-1 pull request #24
Opened 2021-03-08 11:00 UTC by alser3217

2021-03-13 20:07 UTC, alvls requested changes

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +    Polynomials(double power) :power(0)
Если я верно понял идею, то здесь power - это не степень. Тогда имя нужно сменить.

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +    int polynomialsGetValue(int point);
Лишний префикс во всех этих методах. Итак понятно, что они из класса Полином

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +class Polynomials;
Почему множественное число в имени класса? Это полином (один).

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +    p = new int[power + 1];
Утечка памяти в этом месте.

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +}
Функция называется setCoefficients. И в параметрах Полином. Я бы ожидал, что она в этот полином и установит коэффициенты. А этого почему-то не происходит. Почему?

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +int Polynomials::polynomialsGetValue(int point)
Вообще, полином должен вычисляться в вещественных числах. Но, поскольку у вас коэффициенты целые, слишком много переделывать.

2021-03-13 20:07 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +    int i = 0;
Нет защиты от самоприсваивания.

2021-03-14 07:04 UTC, alser3217 commented on raschetnov_as/task2/Source.cpp
> +    Polynomials(double power) :power(0)
Не очень понятно, что Вы имели в виду, потому что непонятно как воспринимать комментарии с кодом на гитхабе, тут 4 строки дано, непонятно куда смотреть. Если Вы про 22 строку, то это - конструктор преобразования, на случай если пользователь класса захочет провести операции класса между полиномами и скалярами, поэтому power = 0 - это полином нулевой степень, т.е. константа.

2021-03-14 07:10 UTC, alser3217 commented on raschetnov_as/task2/Source.cpp
> +}
Эта функция в принципе не является частью класса, она просто заполняет какой-то массив элементами. Может её вообще убрать ? Пользователь сам разберётся каким способом ему удобнее заполнить массив и потом уже будет передавать его в метод класса. Или я могу эту функцию переименовать и просить на вход только степень полинома, но тогда пользователю придётся держать в голове степень каждого объекта или же при вызове передавать метод класса, который эту степень возвращает.

2021-03-14 14:53 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +    Polynomials(double power) :power(0)
1. Комментарий я всегда указываю для первой строки над ним.
2. Вы назвали power параметр конструктора. Во-первых, это плохо, потому что в классе есть поле с таким именем. Во-вторых, судя по коду - это не степень, а коэффициент, поскольку вы его присваиваете в массив коэффициентов.

2021-03-14 14:55 UTC, alvls commented on raschetnov_as/task2/Source.cpp
> +}
Тут решайте сами, лишь бы поведение функции соответствовало ожиданиям, которые возникают из ее прототипа.

2021-03-14 15:15 UTC, alser3217 commented
Подскажите ещё насчёт перегрузки оператора умножения. Тут он не перегружен как оператор сложения, чтобы пользователь не пытался умножить два объекта класса, из-за этого приходится писать две одинаковые функции на случай правого и левого операндов. Может можно по-другому как-то это реализовать ?

2021-03-14 15:36 UTC, alvls commented
Если не делать умножение полиномов, то кроме способа, что вы уже реализовали, есть только вариант сделать умножение полинома на число в виде метода класса. Правда, этот способ потеряет симметрию. Так что я бы сделал также, как вы.

2021-03-14 16:20 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,2
Штраф: | 0,0
__Итого:__ | 6,2

2021-03-14 16:20 UTC, merged