tsk 2.Matrix.Tsvetkov A.A.
alvls/mp1-2021-1 pull request #25
Opened 2021-03-08 18:57 UTC by a1xsa

2021-03-13 20:29 UTC, alvls commented
Алексей, использование malloc/free на С++ возможно, но не слишком приветствуется. Лучше, удобнее и понятнее new/delete. Можете в этот раз оставить, но на будущее учтите.
Проверьте и исправьте огрехи в оформлении кода (местами).

2021-03-14 13:43 UTC, a1xsa commented
У меня есть версия с new/delete , возникли некоторые проблемы и не успел доделать к 8 числу, поэтому отправил что было. Сейчас могу с new/delete

2021-03-14 14:56 UTC, alvls commented
> 
> 
> У меня есть версия с new/delete , возникли некоторые проблемы и не успел доделать к 8 числу, поэтому отправил что было. Сейчас могу с new/delete

Оставьте, как сделали. Поправьте оформление.

2021-03-14 21:27 UTC, a1xsa commented
Вроде подправил, что увидел

2021-03-15 06:25 UTC, alvls requested changes

2021-03-15 06:25 UTC, alvls commented on tsvetkov_aa/task2/Source.cpp
> +
Лишние пустые строки

2021-03-15 06:25 UTC, alvls commented on tsvetkov_aa/task2/Source.cpp
> +			for ( j = 0; j < size; j++)
Цикл по j оформлен неверно (см. цикл по i)

2021-03-15 06:25 UTC, alvls commented on tsvetkov_aa/task2/Source.cpp
> +
Лишняя пустая строка

2021-03-15 06:25 UTC, alvls commented on tsvetkov_aa/task2/Source.cpp
> +
Лишняя пустая строка

2021-03-15 06:25 UTC, alvls commented on tsvetkov_aa/task2/Source.cpp
> +		int i=0,j=0, s;
Не хватает пробелов

2021-03-15 06:26 UTC, alvls commented
Алексей, я указал несколько огрехов в оформлении в качестве примера. Пройдите по коду и исправьте их и остальные такие же.

2021-03-15 09:33 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,0
Качество   проектирования: | 1,5
Качество кода: | 1,5
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,0

2021-03-15 09:33 UTC, merged