task3 Kolesnikov_DE
alvls/mp1-2021-1 pull request #30
Opened 2021-03-20 20:47 UTC by kde37777

2021-03-25 12:45 UTC, alvls requested changes

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +                mass[i].tword = new string [5];
Почему тут 5?

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +            delete [] mass;
Зачем delete?

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +            return "1";
Почему "1"?

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +        int Is_There(string wd)
Почему не bool?

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +        int Ch_Tr(string wd,string twd,int num = 1)
Почему не bool?

2021-03-25 12:45 UTC, alvls commented on Kolesnikov_DE/task3/task3.cpp
> +        int Add_Tr(string wd,string twd)
Почему не bool?

2021-03-25 16:14 UTC, kde37777 commented
Прошу прощения,с delete опечатка

2021-03-26 11:17 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,1
Штраф: | 0,0
__Итого:__ | 8,1

2021-03-26 11:18 UTC, merged