Task 3
alvls/mp1-2021-1 pull request #31
Opened 2021-03-21 08:37 UTC by AndreyBugrov

2021-03-21 08:43 UTC, AndreyBugrov commented on bugrov_av/template/task3/Integral.cpp
> +		}
Скажите, почему в чём у меня неверно в блоке, начиная с 
else 
{
a = s[i]-'0';
...
}
Почему-то у меня atof отбрасывает дробную часть. Поэтому я сам попытался реализовать её. Но в моей реализации дробная часть записывается неверно

2021-03-21 11:47 UTC, AndreyBugrov commented on bugrov_av/template/task3/Integral.cpp
> +		}
Всё, я разобрался

2021-03-25 14:15 UTC, alvls requested changes

2021-03-25 14:15 UTC, alvls commented on bugrov_av/template/task3/Integral.cpp
>  	void GetLim(double l, double r)// ������ ������� ��������������
Это не Get, это Set

2021-03-25 14:15 UTC, alvls commented on bugrov_av/template/task3/Integral.cpp
>  	const double* OutLim()// ����� �������� ��������������
А вот это Get.
Далее аналогично.

2021-03-26 13:44 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2021-03-26 13:45 UTC, merged