Zbruev_DA_task_3
alvls/mp1-2021-1 pull request #33
Opened 2021-03-21 11:05 UTC by DenisZbruev

2021-03-25 16:54 UTC, alvls requested changes

2021-03-25 16:54 UTC, alvls commented on Zbruev_DA/task3/Source.cpp
> +		}
Зачем это делать, если сразу далее память удаляется?

2021-03-25 16:54 UTC, alvls commented on Zbruev_DA/task3/Source.cpp
> +			std::cout << " ";
Такой способ работает только если экран пуст. Иначе позиция вывода будет неверной

2021-03-25 16:54 UTC, alvls commented on Zbruev_DA/task3/Source.cpp
> +			t.setstr(s);
Ввод должен обеспечивать сам класс "Однострочный текстовый редактор".

2021-03-25 19:13 UTC, DenisZbruev commented
  25.03.2021, 19:54, "Alexander Sysoyev" ***@***.******@***.*** requested changes on this pull request.In Zbruev_DA/task3/Source.cpp:> +		for (i = 0; i < size; i++)//������ � ������ ����
+		{
+			str[i] = 0;
+		}
Зачем это делать, если сразу далее память удаляется?In Zbruev_DA/task3/Source.cpp:> +		for (int i = 0; i < num_whitespace; i++)
+			std::cout << "\n";
+		for (int i = 0; i < indent_line; i++)
+			std::cout << " ";
Такой способ работает только если экран пуст. Иначе позиция вывода будет невернойIn Zbruev_DA/task3/Source.cpp:> +			std::cout <<"������� ������: ";
+			t.set_cursor();
+			std::cin >> s;
+			t.setstr(s);
Ввод должен обеспечивать сам класс "Однострочный текстовый редактор".—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-03-26 13:54 UTC, alvls commented
Пункт 6) обеспечить ввод пользователем строки с длиной не больше длины поля ввода
выполнен частично. Вводить можно строку произвольной длины. Кроме того, при закрытии программа падает, вероятно, проблемы с памятью.
Поскольку на исправление времени не осталось, я засчитаю, как есть.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,5
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,5

2021-03-26 17:05 UTC, merged