task3
alvls/mp1-2021-1 pull request #34
Opened 2021-03-21 11:12 UTC by alser3217

Коммит с ошибкой, должно быть task3.

2021-03-25 21:15 UTC, alvls requested changes

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +  double* limits;
Проще и удобнее было бы сделать два поля. Не пришлось бы отдельно выделять и удалять память

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    int i = 0;
Зачем эта переменная?

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +  limits = new double[2];
Утечка памяти

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +  return limits;
Теперь limits можно испортить извне класса...

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +      result = this->leftRiemannSum();
Зачем здесь this?

2021-03-25 21:15 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Почему эта проверка здесь? Она должна быть в другом месте.

2021-03-26 09:30 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Если эту проверку делать не здесь, то её придётся делать два раза: в функции setLimits и в конструкторе. К тому же, непонятно как доложить пользователю класса об этой ошибке, потому что конструктор вернуть ничего не может, а функция если и вернёт что-то, то это потом всё равно надо будет проверять.

2021-03-26 09:42 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
> 
> 
> Если эту проверку делать не здесь, то её придётся делать два раза: в функции setLimits и в конструкторе. 

Да. Но как у вас хуже, поскольку проверяете вы не там, где поступили неверные данные.

> К тому же, непонятно как доложить пользователю класса об этой ошибке, потому что конструктор вернуть ничего не может, а функция если и вернёт что-то, то это потом всё равно надо будет проверять.

Именно поэтому мы рассматривали исключения.

2021-03-26 09:56 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Я думал, что исключения необходимы в тех ситуациях, в которых если их не обработать, то программа будет снята с исполнения. В этом случае получится просто неверный результат.

2021-03-26 10:00 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Не совсем так. В случае, если указаны неверные пределы интегрирования, фактически нарушены входные условия для этого класса, т.е. такой объект существовать не должен. Исключение в этом случае вполне подходящий способ обработки.

2021-03-26 10:25 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Если этот объект не должен существовать, то и нет никакого смысла продолжать выполнение программы, т.е. её нужно принудительно завершить. Это делается с помощью функции exit() ?

2021-03-26 10:43 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
> 
> 
> Если этот объект не должен существовать, то и нет никакого смысла продолжать выполнение программы, т.е. её нужно принудительно завершить. Это делается с помощью функции exit() ?

Не обязательно. Если вы можете запросить новые данные (в коде, который пытался создать объект), то, перехватив исключение, можно получить другие значения и попробовать снова. Главное, что класс (с помощью исключения) сообщил об ошибке и не дал использовать неверно сконструированный объект.

2021-03-26 10:50 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
А как запросить новые данные, если не просить ввести их с клавиатуры ? В методах класса вроде как не должно быть ввода с консоли.

2021-03-26 10:54 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    cout << "ENTER PROPER LIMITS" << endl;
Это будет в вызывающем коде, там, где перехватывается исключение. Например, в функции main

2021-03-26 13:59 UTC, alvls requested changes

2021-03-26 13:59 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +}
Зачем такой метод? Вы вернули только левую границу.

2021-03-26 13:59 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    }
Неверно. В конструкторе нужно только бросить исключение. Ловить и обрабатывать его должен код, из которого вызывается этот конструктор. То же самое касается и метода setLimits

2021-03-26 15:09 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    }
А как поймать исключение, брошенное конструктором ? Он вызывается при создании объекта, но я же не могу объявление объектов поместить в блок try. Если только вместе с ними вообще весь код, который содержится в main поместить в try.

2021-03-26 17:06 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    }
> Он вызывается при создании объекта, но я же не могу объявление объектов поместить в блок try. 

Почему это? Конечно, можете.

2021-03-26 17:15 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    }
Я пробовал помещать в блок try только само создание объектов, но компилятор в последующем коде почему-то не видит эти объекты.
<img width="728" alt="temp" src="https://user-images.githubusercontent.com/71322759/112668778-f3ef6a80-8e6f-11eb-8636-f0a83f38b15d.png">

2021-03-26 17:36 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    }
Все верно. Нужно поместить в блок try весь код, связанный с этим объектом. По факту это может быть весь код функции main

2021-03-26 17:37 UTC, alser3217 commented on raschetnov_as/task3/Source.cpp
> +    }
При помещении переменных в блок try они становятся что-то типа локальными и видны только в этом блоке ?

2021-03-26 20:32 UTC, alvls commented on raschetnov_as/task3/Source.cpp
> +    }
Не что-то типа, а именно локальными. По общим правилам языка С++

2021-03-26 20:32 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2021-03-26 20:32 UTC, merged