ver1.0 task 4 Krainev
alvls/mp1-2021-1 pull request #39
Opened 2021-04-02 17:39 UTC by AlexanderOfficial

2021-04-06 14:52 UTC, alvls requested changes

2021-04-06 14:52 UTC, alvls commented on Krainev_AA/task4/Source.cpp
> +		else { numberOfMemberFamily[searchMember(otherDay, otherMonth, otherYear)].weightMember = otherWeight; }
Неэффективно дважды вызывать `searchMember`

2021-04-06 14:52 UTC, alvls commented on Krainev_AA/task4/Source.cpp
> +			if (numberOfMemberFamily[j].dateInWeight.day == otherDay\
Зачем `\` в конце строки?

2021-04-06 14:52 UTC, alvls commented on Krainev_AA/task4/Source.cpp
> +	vector <Weight> numberOfMemberFamily;
Что хранит `numberOfMemberFamily`?

2021-04-06 14:52 UTC, alvls commented on Krainev_AA/task4/Source.cpp
> +struct memberFamily {
Лучше `memberOfFamily` или `familyMember`. Далее есть аналогичные идентификаторы.

2021-04-06 14:54 UTC, alvls commented
Александр, в целом очень хорошо. Есть несколько "стилевых" замечаний и одно по эффективности. Плюс проверьте код на предмет единообразия в стиле кодирования.

2021-04-06 15:05 UTC, AlexanderOfficial commented on Krainev_AA/task4/Source.cpp
> +			if (numberOfMemberFamily[j].dateInWeight.day == otherDay\
https://rsdn.org/forum/cpp/1277458.all увидел тут, вот и использую, 
можно вообще ничего не указывать?

2021-04-06 15:31 UTC, alvls commented on Krainev_AA/task4/Source.cpp
> +			if (numberOfMemberFamily[j].dateInWeight.day == otherDay\
Это способ для макросов. Для обычного кода он не нужен. Если убрать слеш, ничего не поменяется.

2021-04-06 19:13 UTC, AlexanderOfficial commented on Krainev_AA/task4/Source.cpp
> +	vector <Weight> numberOfMemberFamily;
Название, конечно, не очень подходит, numberOfMemberFamily хранит вектор, каждый элемент которого "характеризует" пользователя (вес и дата). В новой версии дал название informationAboutWeightDate.

2021-04-08 14:41 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 8,0

2021-04-08 14:41 UTC, merged