task4 Kolesnikov_DE
alvls/mp1-2021-1 pull request #43
Opened 2021-04-04 15:47 UTC by kde37777

2021-04-06 20:09 UTC, alvls requested changes

2021-04-06 20:09 UTC, alvls commented on Kolesnikov_DE/task4/task4.cpp
> +	int n, dynl, inhour,year;
Переменным и, тем более, полям класса желательно давать имена, из которых можно понять их назначение. Что означают эти поля, непонятно.

2021-04-06 20:09 UTC, alvls commented on Kolesnikov_DE/task4/task4.cpp
> +    int CntOfR[12] = { 0 };
И это тоже

2021-04-06 20:09 UTC, alvls commented on Kolesnikov_DE/task4/task4.cpp
> +	void operator= (const Termo&){};
Поправьте оформление кода. Отступы то пробелами, то табуляцией.

2021-04-06 20:09 UTC, alvls commented on Kolesnikov_DE/task4/task4.cpp
> +    Termo(const Termo& other)
Конструктор копирования написан с ошибками - проблемы с памятью.

2021-04-06 20:09 UTC, alvls commented on Kolesnikov_DE/task4/task4.cpp
> +        if(n){return false;}
Что означает это условие?

2021-04-07 14:41 UTC, kde37777 commented
Исправил

2021-04-07 14:59 UTC, kde37777 commented
Исправил

2021-04-07 17:03 UTC, kde37777 commented
Исправил

2021-04-09 09:02 UTC, alvls commented
Денис, методы класса нужно не просто написать, но еще и протестировать. Для этого есть два варианта: 1) написать "обычную" программу с меню и набором функций из постановки задачи, которая использует все методы класса; 2) написать простой код, который тестирует все методы класса с разными вариантами входных параметров.
Поскольку у вас нет не того, ни другого, вы допускаете ошибки в коде (это нормально), и потом не имеете шансов их обнаружить (а вот это нехорошо).
Я их вижу в силу большого опыта, знания типовых ошибок, и небольшого объема вашего кода, что позволяет мне весь его просмотреть.
В качестве иллюстрации тезиса: я написал про ошибку в конструкторе копирования, вы ее исправили. Но проблема в том, что точно такая же ошибка есть и в других методах класса, где вы работаете с памятью. И там вы ее не заметили.
Кстати, избежать этих проблем можно, если вместо динамических массивов использовать `std::vector`, поскольку он сам выделит и удалит память, когда нужно.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,5
Качество   проектирования: | 1,7
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,2

2021-04-09 17:37 UTC, merged