Task 4
alvls/mp1-2021-1 pull request #44
Opened 2021-04-04 17:48 UTC by Sergey-Zagrebin

2021-04-06 20:34 UTC, alvls commented on zagrebin_sy/task4/Source.cpp
> +	unsigned int year : 15;
Есть ли смысл в этой экономии памяти?

2021-04-06 20:36 UTC, alvls requested changes

2021-04-06 20:36 UTC, alvls commented on zagrebin_sy/task4/Source.cpp
> +			throw err::wrong_date;
Лучше вызвать вторую версию оператора, чтобы не дублировать код

2021-04-06 20:36 UTC, alvls commented on zagrebin_sy/task4/Source.cpp
>  	list<Song> l;
Имя l ужасно. Назовить, например, songs

2021-04-06 20:37 UTC, alvls commented
В целом весьма хороший код. Есть несколько замечаний (см. выше).

2021-04-08 19:59 UTC, Sergey-Zagrebin commented on zagrebin_sy/task4/Source.cpp
> +	unsigned int year : 15;
Но ведь нам никогда не пригодится запас дней в месяце. Поэтому мне показалось это оптимальным.

2021-04-08 21:30 UTC, alvls commented
__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 2,0
Качество кода: | 2,0
Бонус: | 0,3
Штраф: | 0,3
__Итого:__ | 8,0

2021-04-08 21:30 UTC, merged