Zbruev_DA_Task4
alvls/mp1-2021-1 pull request #48
Opened 2021-04-04 20:54 UTC by DenisZbruev

2021-04-08 14:00 UTC, alvls requested changes

2021-04-08 14:00 UTC, alvls commented on Zbruev_DA/task4/Source.cpp
> +	std::vector<struct Film> F;
В С++ не надо использовать `struct Film`, достаточно просто `Film`

2021-04-08 14:00 UTC, alvls commented on Zbruev_DA/task4/Source.cpp
> +		TMP.clear();//������� ������ ���������� �������
Неудачная реализация. Вместо этого можно в том же векторе F "сдвинуть" элементы с номера delete_num+1 до конца на одну позицию влево. Еще один вариант - использовать метод вектора erase

2021-04-08 14:00 UTC, alvls commented on Zbruev_DA/task4/Source.cpp
> +		return(film);
А если фильм не найден, что возвращается?

2021-04-08 14:00 UTC, alvls commented on Zbruev_DA/task4/Source.cpp
> +		F.clear();
Не нужно этого делать. Вектор будет удален автоматически.

2021-04-09 15:30 UTC, DenisZbruev commented
  08.04.2021, 17:00, "Alexander Sysoyev" ***@***.******@***.*** requested changes on this pull request.In Zbruev_DA/task4/Source.cpp:>  	int year, month, day;//���� ������
 	int fees;//�����
+};
+class Filmoteka
+{
+	int size;//����� ������� � ����������
+	std::vector<struct Film> F;
В С++ не надо использовать struct Film, достаточно просто FilmIn Zbruev_DA/task4/Source.cpp:> +		for (i = 0; i < delete_num; i++)//��������� � tmp ��� ����� ������� F �� ������ tmp_num
+		{
+			TMP.push_back(F[i]);// = F[i];
+		}
+		for (i = delete_num + 1; i < size; i++)//��������� � tmp ��� ����� ������� F ����� ������ tmp_num
+		{
+			TMP.push_back(F[i - 1]);
+		}
+		F.clear();//����� ������ ������ F � ������������ � ���� ��� �������� tmp
+		for (i = 0; i < size; i++)
+		{
+			F.push_back(TMP[i]);
+		}
+		TMP.clear();//������� ������ ���������� �������
Неудачная реализация. Вместо этого можно в том же векторе F "сдвинуть" элементы с номера delete_num+1 до конца на одну позицию влево. Еще один вариант - использовать метод вектора eraseIn Zbruev_DA/task4/Source.cpp:> +		return(TMP);
+		TMP.clear();
+	}
+	struct Film find_film_by_name_and_year(string name, int year)//����� ����� �� �������� � ����
+	{
+		int i;
+		struct Film film;
+		for (i = 0; i < size; i++)//���� ���������� ������� � ���������� ��� � film
+		{
+			if ((F[i].year == year)&&(F[i].film_name==name))
+			{
+				film= F[i];
+				break;
+			}
+		}
+		return(film);
А если фильм не найден, что возвращается?In Zbruev_DA/task4/Source.cpp:> +		F.push_back(Temp);//��������� � ����� ������������ �����
+		swap(F[film_num], F.back());//������ ��� ������� � ���������� �������
+		F.pop_back();//�������� ���������� ������
+	}
+	vector <struct Film> get_all_films()//������ ��� ������
+	{
+		return(F);
+	}
+	int get_size()//������ ������� ����� �������
+	{
+		size = F.size();
+		return (size);
+	}
+	~Filmoteka()//����������
+	{
+		F.clear();
Не нужно этого делать. Вектор будет удален автоматически.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  Денис Збруев 

2021-04-09 21:45 UTC, alvls commented
Денис, замечания по вашей реализации:
1. Вы исправили метод `delete_film`, однако в методе `setfilm` та же проблема. Для нее решением является метод insert из класса `std::vector`. Даже не зная о его наличии, можно было предположить, что раз есть удаление из середины, то может быть и вставка в середину.
2. У вас в классе нет метода "изменить данные выбранного фильма". Вместо этого вы удаляете фильм, а потом вставляет его заново.
3. Проблема с пунктом 2 была бы решена, если бы вы правильно реализовали метод "найти фильм по названию и году", на что я намекал в замечании. В первом семестре мы рассматривали поиск в массиве, где результатом является индекс элемента. Здесь было бы правильно реализовать такую же идею. И добавить перегрузку оператора[].

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,3
Качество   проектирования: | 1,8
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,1

2021-04-12 10:50 UTC, merged