task4
alvls/mp1-2021-1 pull request #49
Opened 2021-04-04 21:10 UTC by alser3217

10 минут не считается (⇀‸↼‶)

2021-04-05 09:29 UTC, alser3217 commented
Решил добавить перегрузку оператора присваивания, только ради проверки на самоприсваивание.

2021-04-08 14:14 UTC, alvls requested changes

2021-04-08 14:14 UTC, alvls commented on raschetnov_as/task4/Source.cpp
> +  return 0;
Почему функция main пуста? Должна быть, если и не полноценная программа, то по крайней мере проверка всех методов класса. Иначе непонятно, тестировали вы их вообще или нет.

2021-04-10 13:23 UTC, alser3217 commented
Гит решил не уведомлять меня о том, что Вы запросили изменения, я просто зашёл сюда и увидел их.

2021-04-12 11:25 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.h
> +  void deleteContact(const int& index);
1. При передаче базовых типов нет смысла использовать ссылку (если только вы не хотите так вернуть из функции значение) - выигрыша по времени и памяти вы не получите.
2. У вас несогласован интерфейс класса. В данном методе нужен индекс для удаления контакта. Но в классе нет метода, который бы этот индекс позволял узнать. При этом методы поиска возвращают не индекс, а копию объекта.

2021-04-12 11:28 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
Когда мы что-то ищем, отсутствие объекта - один из возможных результатов (корректных), поэтому должен быть способ об этом программно узнать (не в виде вывода на консоль). Например, вернуть bool или индекс.

2021-04-12 11:28 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.cpp
> +  }
Крайне неудачный вариант - выводить здесь на консоль!

2021-04-12 11:33 UTC, alvls commented
Алексей, в коде есть существенные проблемы с проектированием. Если сегодня исправите, повышу оценку. А пока так.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 3,3
Качество   проектирования: | 1,2
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 6,5



> 
> 
> Гит решил не уведомлять меня о том, что Вы запросили изменения, я просто зашёл сюда и увидел их.

Это крайне странно.

2021-04-12 13:23 UTC, alser3217 commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
Не понимаю замечаний по поводу отсутствия объекта. Если в методах, где нужно найти какой-то объект по какому-то признаку, такого метода не находится, то я вывожу сообщение об этом на консоль и возвращаю объект, инициализированный с помощью конструктора по умолчанию. Чем плоха такая реализация ?

2021-04-12 13:23 UTC, alser3217 commented on raschetnov_as/task4/ClassContactsStorage.cpp
> +  }
Почему ?

2021-04-12 14:30 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
Плохо тем, что вывод на консоль - это информация для пользователя, а программно узнать, что объект не найден вы не можете. Т.е. не может написать условие вида
```
if (<объект не найден>)
  <что-то делаем>
```

2021-04-12 14:34 UTC, alser3217 commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
Как же не можем, если я возвращаю несуществующий объект, в случае если объект не найден ?

2021-04-12 14:37 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.cpp
> +  }
Причину см. выше.

2021-04-12 14:38 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
И как вы напишете такую проверку?

2021-04-12 14:44 UTC, alser3217 commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
Речь идёт о проверке, которая дальше по коду может использоваться, а не конкретно в методе ? К примеру, вызвали метод поиска контакта по номеру телефона, он что-то вернул. Затем, в каком-то другом месте проверка по типу: если(то, что вернул тот метод), то сохранить его в файл, к примеру ?

2021-04-12 14:48 UTC, alvls commented on raschetnov_as/task4/ClassContactsStorage.h
> +  Contact contactByPhoneNumber(string _phoneNumber);
да

2021-04-12 22:18 UTC, alvls commented
Стало несколько лучше. Итоговая оценка.

__Работа   принята__ |  
-- | --
__Ваш текущий балл:__ |  
Функциональность: | 4,0
Качество   проектирования: | 1,4
Качество кода: | 2,0
Бонус: | 0,0
Штраф: | 0,0
__Итого:__ | 7,4

2021-04-12 22:18 UTC, merged